project:
  type: book
  preview:
    browser: true

book:
  title: "New Zealand Soil Classification v3.0"
  author: "Alan. E. Hewitt"
  date: "2022-10-10"
  isbn: 978-0-478-34710-4
  cover-image: images/cover.png
  search: false
  repo-url: https://github.com/lauren-obrien/nzsc_v3
  chapters:
    - index.qmd
    - Foreword.qmd
    - Introduction.qmd
    - Diagnostics.qmd
    - Key-to-Orders.qmd
    - Allophanics.qmd
    - Anthropics.qmd
    - Browns.qmd
    - Gleys.qmd
    - Granulars.qmd
    - Melanics.qmd
    - Organics.qmd
    - Oxidics.qmd
    - Pallics.qmd
    - Podzols.qmd
    - Pumices.qmd
    - Raws.qmd
    - Recents.qmds
    - Semiarids.qmd
    - Ultics.qmd
    - Acknowledgements.qmd
    - Appendix.qmd
    - references.qmd


bibliography: NZSC_reference_list_3e.bib
#csl: geoderma.csl

format:
  html:
    theme:
      light: cosmo
      dark: slate
    number-sections: false
    citations-hover: true
  epub:
    number-sections: false

editor: visual

# global knitr options
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    out.width: '85%'
    fig.align: 'center'
    echo: false
    fig.show: 'hold'
    results: 'hold'

# leftover from _common.R:
# example R options set globally
#options(width = 60)
