# Allophanic Soils {#sec-ord-L}

## Concept of the Order {#sec-con-L}

Allophanic Soils have properties that are strongly influenced by minerals with short-range order, especially allophane, imogolite and ferrihydrite. They are characteristically weak in strength and sensitive, with very low bulk density. They occur mostly in volcanic parent materials, especially ash and basaltic scoria, but occur also in quartzo-feldspathic and tuffaceous (greywacke) sandstone.

## Correlation {#sec-cor-L}

The order comprises mainly yellow-brown loams but also includes weakly weathered red loams and brown loams and some upland and high country yellow-brown earths of the NZ Genetic Soil Classification. The soils correlate predominantly with the Aquands, Cryands and Udands of Soil Taxonomy.

## Occurrence {#sec-occ-L}

Allophanic Soils occur predominantly in North Island volcanic ash, and in the weathering products of other volcanic rocks. They also occur in the weathering products of greywacke and schist in the South Island high country.

## Accessory Properties of the Order {#sec-acc-L}

1.  *Short-range-order minerals.* The soil matrix as well as pore surfaces are dominated by the clay minerals allophane, imogolite and ferrihydrite, and/or aluminium-humus complexes. The soil materials have very high specific surface area. Measured clay contents generally range from 10 to 25% though particle-size measurement is difficult because of aggregation and the "true" or primary clay contents may often be considerably higher. P retention is high or very high.
2.  *Low bases.* Sum of bases are low to very low and range from less than 1 to 10 cmol/100 g in subsoils and unfertilised topsoils.
3.  *Volcanic or greywacke parent materials.* Predominantly in andesitic, rhyolitic or mixed tephra, they also occur in soil materials from sandstone (greywacke) of humid uplands and high country and basalt scoria or pumice.
4.  *Rapidly weatherable minerals.* Volcanic glass and feldspar dominate the sand fractions of soils in igneous parent materials, and are the primary source of the short-range-order minerals. Feldspars are most likely the primary source in non-igneous parent materials. Typically they have an Amorphic mineralogy class.
5.  *Rapid permeability and high water retention.* The macroporosity is very high and rapid drainage occurs at low soil moisture tensions. Water contents at 1500 kPa soil moisture tension are very high.
6.  *Well drained.* Although poorly, imperfectly and moderately well drained soils occur, well drained soils are predominant.
7.  *Good rooting medium.* Bulk density is very low and there is little resistance to root extension. In many soils the potential rooting depth is very deep.
8.  *Active soil fauna.* Microbial biomass is generally high.
9.  *Stable topsoils.* Soils resist puddling under the impact of machinery or grazing animals in wet weather. The water content at field capacity is less than the plastic limit. Topsoil and subsoil horizons are friable, and organic/mineral complexes are stable. Carbon contents are medium to high. Exposed topsoil may be subject to wind erosion.
10. *High shrinkage potential.* Soil materials have high potential to shrink on drying. Rewetting may not achieve the original volume.
11. *Slight to insignificant erosion under pasture.* Generally the erosion potential is low, except on steep slopes or exposed sites and under cultivation on rolling slopes.
12. *Sensitive.* A pronounced loss of strength occurs on disturbance.
13. *Limited fertility.* There are usually requirements for phosphorus, potassium and magnesium on dairy farms. There are no significant trace element deficiencies although cobalt is marginal in more strongly leached Allophanic Soils. Pasture may respond to lime where pH is less than 5.3. Sulphate reserves are held in B horizons. P retention and phosphate fixation are high in topsoils.
14. *Moist climate.* Precipitation exceeds 1000 mm and soil moisture deficits are either absent or occur for only short periods.

## Summary of Allophanic Soils Hierarchy {#sec-sum-L}

```{r}

library(flextable)

table_L <- data.frame(
  'Code' = c(rep('LP', 2),
             rep('LG', 2),
             rep('LI', 3),
             rep('LO', 5)),
  'Group' = c(rep('Perch-gley', 2), 
              rep('Gley', 2),
              rep('Impeded', 3),
              rep('Orthic', 5)),
  'Subgroup' = c('Ironstone', 'Typic',
                 'Peaty', 'Typic',
                 'Mottled-Ironstone', 'Mottled', 'Typic',
                 'Mottled', 'Vitric-Acidic', 'Vitric', 'Acidic', 'Typic'),
  'Example_Series' = c('-', 'Awatuna',
                       'Rahotu var.', 'Glenn',
                       'pt. Okato var.', 'Tipoka', 'Bruntwood',
                       'Oeo', 'Rowan', 'Lepperton', 'Patua', 'Tirau')
) 

ft_L <- flextable(table_L, 
                  col_keys = c('Code', 'Group', 'Subgroup', 'Example_Series'))
ft_L <- bold(ft_L, part = 'head')
ft_L <- merge_v(ft_L, 1)
ft_L <- merge_v(ft_L, 2)
ft_L <- valign(ft_L, j = c(1,2), valign = 'top')
ft_L <- bold(ft_L, j = 1)
ft_L <- set_table_properties(ft_L, layout = "autofit", width = 1)
ft_L <- set_header_labels(ft_L, 
                          'Example_Series' = 'Example Series')
ft_L
```

------------------------------------------------------------------------

## Key to Groups of Allophanic Soils {#sec-grp-L}

#### **LP** {#sec-key-LP}

Allophanic Soils that have both

1.  [Perch-gley features](Diagnostics.qmd#sec-diag-pgley), *and*
2.  Either a [peaty topsoil](Diagnostics.qmd#sec-diag-pts), or within 15 cm of the base of the A horizon or 30 cm of the mineral soil surface, have
    (a) a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh), *or*
    (b) a [redox-mottled horizon](Diagnostics.qmd#sec-diag-roxh) if the parent material is predominantly andesitic or basaltic.

::: {style="text-align: right"}
[**PERCH-GLEY ALLOPHANIC SOILS**](#sec-LP)
:::

#### **LG** {#sec-key-LG}

Other Allophanic Soils that have a [peaty topsoil](Diagnostics.qmd#sec-diag-pts), or within 15 cm of the base of the A horizon or 30 cm of the mineral soil surface, have either

1.  a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh), ***or***
2.  a [redox-mottled horizon](Diagnostics.qmd#sec-diag-roxh) if the parent material is predominantly andesitic or basaltic.

::: {style="text-align: right"}
[**GLEY ALLOPHANIC SOILS**](#sec-LG)
:::

#### **LI** {#sec-key-LI}

Other Allophanic Soils that have a [slowly permeable layer](Diagnostics.qmd#sec-diag-slowp), or horizon that is at least weakly indurated, within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
[**IMPEDED ALLOPHANIC SOILS**](#sec-LI)
:::

#### **LO** {#sec-key-LO}

Other Allophanic Soils.

::: {style="text-align: right"}
[**ORTHIC ALLOPHANIC SOILS**](#sec-LO)
:::

------------------------------------------------------------------------

## Key to Subgroups of Allophanic Soils {#sec-sub-L}

### **LP** - PERCH-GLEY ALLOPHANIC SOILS {#sec-LP}

Perch-gley Allophanic Soils occur in sites that are periodically saturated (unless artificially drained). Wetness and associated reducing conditions are indicated by brownish or reddish mottles. The wetness is caused by the perching of water on a slowly permeable subsurface layer, although a groundwater-table may also be present.

#### **LPI** {#sec-key-LPI}

Perch-gley Allophanic Soils that have an [ironstone-pan](Diagnostics.qmd#sec-diag-ipan) within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Ironstone Perch-gley Allophanic Soils**
:::

#### **LPT** {#sec-key-LPT}

Other soils.

::: {style="text-align: right"}
**Typic Perch-gley Allophanic Soils**
:::

### **LG** - GLEY ALLOPHANIC SOILS {#sec-LG}

Gley Allophanic Soils occur in sites that are periodically saturated (unless artificially drained). Wetness and associated reducing conditions are indicated by brownish or reddish mottles. The wetness is caused by a groundwater-table.

#### **LGO** {#sec-key-LGO}

Gley Allophanic Soils that have a [peaty topsoil](Diagnostics.qmd#sec-diag-pts).

::: {style="text-align: right"}
**Peaty Gley Allophanic Soils**
:::

#### **LGT** {#sec-key-LGT}

Other soils.

::: {style="text-align: right"}
**Typic Gley Allophanic Soils**
:::

### **LI** - IMPEDED ALLOPHANIC SOILS {#sec-LI}

Impeded Allophanic Soils have a subsurface horizon that acts as a barrier to the movement of water or penetration of roots.

#### **LIMI** {#sec-key-LIMI}

Impeded Allophanic Soils that have an ironstone-pan within 90 cm of the mineral soil surface and that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled-ironstone Impeded Allophanic Soils**
:::

#### **LIM** {#sec-key-LIM}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Impeded Allophanic Soils**
:::

#### **LIT** {#sec-key-LIT}

Other soils.

::: {style="text-align: right"}
**Typic Impeded Allophanic Soils**
:::

### **LO** - ORTHIC ALLOPHANIC SOILS {#sec-LO}

Orthic Allophanic Soils are permeable soils without barriers to deep penetration of roots. They are moderately well, well or imperfectly drained.

#### **LOM** {#sec-key-LOM}

Orthic Allophanic Soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Orthic Allophanic Soils**
:::

#### **LOVA** {#sec-key-LOVA}

Other soils that have both 1. ***either*** (a) coatings on pores (excluding root linings), or gel-like masses bridging sand grains or coating coarse-fragments, that have hue 7.5YR or redder, value 5 or less and chroma 3 or more, *or* (b) pH less than 5.5 in some part of the B horizon to 60 cm from the mineral soil surface, *and* 2. [allophanic soil material](Diagnostics.qmd#sec-diag-alloph) that is formed predominantly from [tephric soil material](Diagnostics.qmd#sec-diag-teph) and has 50% or more sand (by weighted average).

::: {style="text-align: right"}
**Vitric-acidic Orthic Allophanic Soils**
:::

#### **LOV** {#sec-key-LOV}

Other soils in which [allophanic soil material](Diagnostics.qmd#sec-diag-alloph) layers are formed predominantly from [tephric soil material](Diagnostics.qmd#sec-diag-teph) and have 50% or more sand (by weighted average).

::: {style="text-align: right"}
**Vitric Orthic Allophanic Soils**
:::

#### **LOA** {#sec-key-LOA}

Other soils that have, in some part of the B horizon to 60 cm from the mineral soil surface, *either*

1.  coatings on pores (excluding root linings), or gel-like masses bridging sand grains or coating coarse-fragments, that have hue 7.5YR or redder, value 5 or less and chroma 3 or more, *or*
2.  pH less than 5.5 in some part of the B horizon to 60 cm from the mineral soil surface.

::: {style="text-align: right"}
**Acidic Orthic Allophanic Soils**
:::

#### **LOT** {#sec-key-LOT}

Other soils.

::: {style="text-align: right"}
**Typic Orthic Allophanic Soils**
:::
