# Raw Soils {#sec-ord-W}

## Concept of the Order {#sec-con-W}

Raw Soils lack distinct topsoil development or are fluid at a shallow depth. They occur in environments where the development of topsoils is prevented by rockiness, by active erosion, or deposition. They include beach sands, alpine rock areas and active screes, lagoons and tidal estuaries.

## Correlation {#sec-cor-W}

Raw Soils correspond in part with very weakly developed recent soils of the NZ Genetic Soil Classification, and in part with materials that were often not considered to be soil. They are either Entisols or are unclassified in Soil Taxonomy.

## Occurrence {#sec-occ-W}

Raw Soils occur scattered throughout New Zealand, particularly in association with high mountains, braided rivers, beaches and tidal mudflats.

## Accessory Properties of the Order {#sec-acc-W}

1.  *No B horizons.* Pedogenetic horizons are lacking apart from a rudimentary topsoil.
2.  *Fresh or weakly weathered.* Coarse fragments and sand particles are generally without coatings, although clasts in some screes may have weathering rinds.
3.  *Inherited mineralogy.* The soil mineralogy is very similar to that of the parent material and a range of mineralogy classes is possible.
4.  *In soils with a fluid subsurface layer, a continuously high water-table is present.* The deposition of fresh sediment may occur.
5.  *Non-fluid soils occur in environments with active erosion or deposition.*
6.  *Low fertility.* Nitrogen in particular, is deficient.
7.  *Erosive.* Most materials are unaggregated and likely to be highly erosive.
8.  *Sparse vegetation.* Vegetation is either absent, sparse or patchy, often consisting of ephemeral herbaceous plants, mosses or lichens. Mangroves occur mainly on Raw Soils.

## Summary of Raw Soils Hierarchy {#sec-sum-W}

```{r}
library(flextable)

table_W <- data.frame(
  'Code' = c(rep('WG', 7), 'WH', 'WX', 'WS', 'WF', 'WT', 'WO'),
  'Group' = c(rep('Gley', 7), 'Hydrothermal', 'Rocky', 'Sandy', 'Fluvial',
                'Tephric', 'Orthic'),
  'Subgroup' = c('Fluid­sulphidic', 'Sulphidic', 'Fluid­saline', 'Saline',
                   'Fluid', 'Sandy', 'Typic',
                 'Active',
                 '-', '-', '-', '-', '-'),
  'Example_Series' = c('pt. Takahiwai', '­', '­', 'pt. Takahiwai', 'pt. Paratai', '­',
                         '­',
                       '-',
                       'pt. Alpine', 'pt. Riverton', 'pt. Selwyn', 'pt. Ngaruhoe',
                         'pt. Alpine')
) 


ft_W <- flextable(table_W)
ft_W <- bold(ft_W, part = 'head')
ft_W <- merge_v(ft_W, 1)
ft_W <- merge_v(ft_W, 2)
ft_W <- valign(ft_W, j = c(1,2), valign = 'top')
ft_W <- bold(ft_W, j = 1)
ft_W <- set_table_properties(ft_W, layout = "autofit", width = 1)
ft_W <- set_header_labels(ft_W, 
                          'Example_Series' = 'Example Series')
ft_W
```

## Key to Groups of Raw Soils {#sec-grp-W}

#### **WG** {#sec-key-WG}

Raw Soils that at 30 cm or less from the mineral soil surface have either

1.  the upper boundary of a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh), *or*
2.  sufficient active ferrous iron to give a positive reaction to α,α'-dipyridyl at some time in the year, *or*
3.  are saturated for 30 or more consecutive days in most years.

::: {style="text-align: right"}
[**GLEY RAW SOILS**](#sec-WG)
:::

#### **WH** {#sec-key-WH}

Other Raw Soils that have mean annual soil temperature at 30 cm depth of at least 2.5°C more than the mean annual air temperature.

::: {style="text-align: right"}
[**HYDROTHERMAL RAW SOILS**](#sec-WH)
:::

#### **WX** {#sec-key-WX}

Other Raw Soils with a [lithic](Diagnostics.qmd#sec-diag-lithc) or [paralithic contact](Diagnostics.qmd#sec-diag-lithp) within 30 cm of the soil surface.

::: {style="text-align: right"}
[**ROCKY RAW SOILS**](#sec-WX)
:::

#### **WS** {#sec-key-WS}

Other Raw Soils that have sand or loamy sand texture and that have less than 35% gravel (by volume) in all horizons, from the soil surface to 60 cm depth or more.

::: {style="text-align: right"}
[**SANDY RAW SOILS**](#sec-WS)
:::

#### **WF** {#sec-key-WF}

Other Raw Soils that have [fluvial features](Diagnostics.qmd#sec-diag-fluv) and are not buried by more than 30 cm of non­fluvial soil material.

::: {style="text-align: right"}
[**FLUVIAL RAW SOILS**](#sec-WF)
:::

#### **WT** {#sec-key-WT}

Other Raw Soils in [tephric soil material](Diagnostics.qmd#sec-diag-teph) from the soil surface to 30 cm depth or more.

::: {style="text-align: right"}
[**TEPHRIC RAW SOILS**](#sec-WT)
:::

#### **WO** {#sec-key-WO}

Other Raw Soils.

::: {style="text-align: right"}
[**ORTHIC RAW SOILS**](#sec-WO)
:::

## Key to Subgroups of Raw Soils {#sec-sub-W}

### **WG** - GLEY RAW SOILS {#sec-WG}

Gley Raw Soils occur in sites that are periodically or permanently flooded. Wetness is expressed in the soil by grey colours with brownish or reddish mottles, by water saturation or is indicated by a chemical test for the presence of reduced iron.

#### **WGFU** {#sec-key-WGFU}

Soils that have both

1.  moderately fluid or very fluid fluidity class at a depth of 30 cm or less, *and*
2.  pH more than 4.0 and pH in boiling hydrogen peroxide less than 3.0, in some horizon at less than 90 cm from the mineral soil surface.

::: {style="text-align: right"}
**Fluid-sulphidic Gley Raw Soils**
:::

#### **WGU** {#sec-key-WGU}

Other soils that have pH more than 4.0 and pH in boiling hydrogen peroxide less than 3.0, in some horizon at less than 90 cm from the mineral soil surface.

::: {style="text-align: right"}
**Sulphidic Gley Raw Soils**
:::

#### **WGFQ** {#sec-key-WGFQ}

Other soils that within 30 cm of the mineral soil surface have both

1.  moderately fluid or very fluid fluidity class, *and*
2.  electrical conductivity of 0.8 mS/cm.

::: {style="text-align: right"}
**Fluid-saline Gley Raw Soils**
:::

#### **WGQ** {#sec-key-WGQ}

Other soils that within 30 cm of the mineral soil surface have electrical conductivity of 0.8 mS/cm or more.

::: {style="text-align: right"}
**Saline Gley Raw Soils**
:::

#### **WGF** {#sec-key-WGF}

Other soils that within 30 cm of the mineral soil surface have moderately fluid or very fluid fluidity class.

::: {style="text-align: right"}
**Fluid Gley Raw Soils**
:::

#### **WGS** {#sec-key-WGS}

Other soils that have sand or loamy sand texture and that have less than 35% gravel (by volume) in all horizons, from the soil surface to 60 cm depth or more.

::: {style="text-align: right"}
**Sandy Gley Raw Soils**
:::

#### **WGT** {#sec-key-WGT}

Other soils.

::: {style="text-align: right"}
**Typic Gley Raw Soils**
:::

### **WH** - HYDROTHERMAL RAW SOILS {#sec-WH}

Hydrothermal Raw Soils occur in active hydrothermal areas affected by hot water.

#### **WHA** {#sec-key-WHA}

(only one subgroup recognised).

::: {style="text-align: right"}
**Active Hydrothermal Raw Soils**
:::

### **WX** - ROCKY RAW SOILS {#sec-WX}

Rocky Raw Soils occur on rock outcrops subject to erosion. The soil volume available to roots is severely restricted.

No subgroups have been defined.

### **WS** - SANDY RAW SOILS {#sec-WS}

Sandy Raw Soils occur in areas of active sand erosion, transportation and deposition, most commonly as dune sands.

No subgroups have been defined.

### **WF** - FLUVIAL RAW SOILS {#sec-WF}

Fluvial Raw Soils occur in sediments deposited by flowing water. They occur on land surfaces on which there is a high risk of flooding.

No subgroups have been defined.

### **WT** - TEPHRIC RAW SOILS {#sec-WT}

Tephric Raw Soils occur in unconsolidated sediments of volcanic origin including ash, cinders, lapilli, pumice and other pyroclastic material.

No subgroups have been defined.

### **WO** - ORTHIC RAW SOILS {#sec-WO}

Orthic Raw Soils occur in land that is being eroded, on rock outcrops or land that has received sediment emplaced primarily by slope processes.

No subgroups have been defined.
